version: "3.8"
services:
  gatsby:
    image: gatsby-docker
    build:
      context: .
      target: production
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - reverse-proxy-network
networks:
  reverse-proxy-network:
    name: reverse-proxy-network
    external: true
